---
include:
  - board: nice_nano_v2
    shield: corne_left nice_view_adapter nice_view
    artifact-name: corne_left
  - board: nice_nano_v2
    shield: corne_right nice_view_adapter nice_view
    artifact-name: corne_right
  - board: eyelash_corne_left
    shield: nice_view
    #snippet: zmk-usb-logging    # Uncomment to log over USB.
    artifact-name: eyelash_corne_left
  - board: eyelash_corne_right
    shield: nice_view
    #snippet: zmk-usb-logging
    artifact-name: eyelash_corne_right
  - board: eyelash_corne_left
    shield: nice_view
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: eyelash_corne_studio_left
  - board: eyelash_corne_left
    shield: settings_reset
    #snippet: zmk-usb-logging
    artifact-name: eyelash_corne_left_settings_reset
  - board: eyelash_corne_right
    shield: settings_reset
    #snippet: zmk-usb-logging
    artifact-name: eyelash_corne_right_settings_reset
